source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'


#pod 'JKCategoryShowKit', :path => 'Desktop/JKCategoryShowKit/JKCategoryShowKit'

target 'JKCategoryShowKit_Example' do
  pod 'JKCategoryShowKit', :path => '../'
  pod 'SDWebImage','~>5.0'
#  pod 'MJRefresh'
#  pod 'MJExtension'
  target 'JKCategoryShowKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
