use_frameworks!

platform :ios, '8.0'

target 'JKCategoryShowKit_Example' do
  pod 'JKCategoryShowKit', :path => '../'

  target 'JKCategoryShowKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
